### ISSUE TITLE
Incomplete type/forward declaration on OpenBSD

### ISSUE THREAD

**Issue by bentley** [valhalla/odin#109]
Attempting to build odin on an OpenBSD 5.8 snapshot (gcc 4.9.2, protobuf 2.4.1) fails with the following error:

    c++ -DHAVE_CONFIG_H -I. -I./valhalla -I/usr/local/include -pthread -pthread -I/usr/local/include -I/usr/include -Ivalhalla -Ivalhalla/proto -O2 -pipe -std=c++11 -MT src/odin/libvalhalla_odin_la-enhancedtrippath.lo -MD -MP -MF src/odin/.deps/libvalhalla_odin_la-enhancedtrippath.Tpo -c src/odin/enhancedtrippath.cc -fPIC -DPIC -o src/odin/.libs/libvalhalla_odin_la-enhancedtrippath.o
    src/odin/enhancedtrippath.cc: In member function 'std::string valhalla::odin::EnhancedTripPath_Edge::ToParameterString() const':
    src/odin/enhancedtrippath.cc:292:38: error: invalid use of incomplete type 'const class google::protobuf::EnumDescriptor'
           TripPath_RoadClass_descriptor()->FindValueByNumber(road_class())->name();
                                          ^
    In file included from /usr/local/include/google/protobuf/generated_message_reflection.h:43:0,
                     from ./valhalla/proto/trippath.pb.h:25,
                     from src/odin/enhancedtrippath.cc:3:
    /usr/local/include/google/protobuf/message.h:138:7: error: forward declaration of 'const class google::protobuf::EnumDescriptor'
     class EnumDescriptor;        // descriptor.h
           ^
    src/odin/enhancedtrippath.cc:308:44: error: invalid use of incomplete type 'const class google::protobuf::EnumDescriptor'
       str += TripPath_Driveability_descriptor()->FindValueByNumber(driveability())
                                                ^
    In file included from /usr/local/include/google/protobuf/generated_message_reflection.h:43:0,
                     from ./valhalla/proto/trippath.pb.h:25,
                     from src/odin/enhancedtrippath.cc:3:
    /usr/local/include/google/protobuf/message.h:138:7: error: forward declaration of 'const class google::protobuf::EnumDescriptor'
     class EnumDescriptor;        // descriptor.h
           ^
    src/odin/enhancedtrippath.cc:359:44: error: invalid use of incomplete type 'const class google::protobuf::EnumDescriptor'
         str += TripPath_TravelMode_descriptor()->FindValueByNumber(travel_mode())
                                                ^
    In file included from /usr/local/include/google/protobuf/generated_message_reflection.h:43:0,
                     from ./valhalla/proto/trippath.pb.h:25,
                     from src/odin/enhancedtrippath.cc:3:
    /usr/local/include/google/protobuf/message.h:138:7: error: forward declaration of 'const class google::protobuf::EnumDescriptor'
     class EnumDescriptor;        // descriptor.h
           ^
    src/odin/enhancedtrippath.cc:366:45: error: invalid use of incomplete type 'const class google::protobuf::EnumDescriptor'
         str += TripPath_VehicleType_descriptor()->FindValueByNumber(vehicle_type())
                                                 ^
    In file included from /usr/local/include/google/protobuf/generated_message_reflection.h:43:0,
                     from ./valhalla/proto/trippath.pb.h:25,
                     from src/odin/enhancedtrippath.cc:3:
    /usr/local/include/google/protobuf/message.h:138:7: error: forward declaration of 'const class google::protobuf::EnumDescriptor'
     class EnumDescriptor;        // descriptor.h
           ^
    src/odin/enhancedtrippath.cc:373:48: error: invalid use of incomplete type 'const class google::protobuf::EnumDescriptor'
         str += TripPath_PedestrianType_descriptor()->FindValueByNumber(pedestrian_type())
                                                    ^
    In file included from /usr/local/include/google/protobuf/generated_message_reflection.h:43:0,
                     from ./valhalla/proto/trippath.pb.h:25,
                     from src/odin/enhancedtrippath.cc:3:
    /usr/local/include/google/protobuf/message.h:138:7: error: forward declaration of 'const class google::protobuf::EnumDescriptor'
     class EnumDescriptor;        // descriptor.h
           ^
    src/odin/enhancedtrippath.cc:380:45: error: invalid use of incomplete type 'const class google::protobuf::EnumDescriptor'
         str += TripPath_BicycleType_descriptor()->FindValueByNumber(bicycle_type())
                                                 ^
    In file included from /usr/local/include/google/protobuf/generated_message_reflection.h:43:0,
                     from ./valhalla/proto/trippath.pb.h:25,
                     from src/odin/enhancedtrippath.cc:3:
    /usr/local/include/google/protobuf/message.h:138:7: error: forward declaration of 'const class google::protobuf::EnumDescriptor'
     class EnumDescriptor;        // descriptor.h
           ^
    src/odin/enhancedtrippath.cc:387:45: error: invalid use of incomplete type 'const class google::protobuf::EnumDescriptor'
         str += TripPath_TransitType_descriptor()->FindValueByNumber(transit_type())
                                                 ^
    In file included from /usr/local/include/google/protobuf/generated_message_reflection.h:43:0,
                     from ./valhalla/proto/trippath.pb.h:25,
                     from src/odin/enhancedtrippath.cc:3:
    /usr/local/include/google/protobuf/message.h:138:7: error: forward declaration of 'const class google::protobuf::EnumDescriptor'
     class EnumDescriptor;        // descriptor.h
           ^
    Error while executing c++ -DHAVE_CONFIG_H -I. -I./valhalla -I/usr/local/include -pthread -pthread -I/usr/local/include -I/usr/include -Ivalhalla -Ivalhalla/proto -O2 -pipe -std=c++11 -MT src/odin/libvalhalla_odin_la-enhancedtrippath.lo -MD -MP -MF src/odin/.deps/libvalhalla_odin_la-enhancedtrippath.Tpo -c src/odin/enhancedtrippath.cc -fPIC -DPIC -o src/odin/.libs/libvalhalla_odin_la-enhancedtrippath.o
    Makefile:1049: recipe for target 'src/odin/libvalhalla_odin_la-enhancedtrippath.lo' failed
    gmake[1]: *** [src/odin/libvalhalla_odin_la-enhancedtrippath.lo] Error 1
    gmake[1]: Leaving directory '/usr/ports/pobj/odin-0.0.0/odin-a1d1668853bacb20f8f479716c3610190dd2c13b'
    Makefile:704: recipe for target 'all' failed
    gmake: *** [all] Error 2

**Comment by bentley** [comment]
This problem went away after I installed protobuf 2.6.1.

**Comment by dgearhart** [comment]
thanks
