### ISSUE TITLE
Traveling this bike path near UCSB results in many maneuvers

### ISSUE THREAD

**Issue by rmglennon** [valhalla/odin#128]
There's a separated, paved bicycle path near UC Santa Barbara that follows along El Colegio Road, connecting student housing on west campus to the main campus. Bike routing along this path (about 1 km) results in separate maneuvers at each location where another edge intersects the route. I've not heard that this bike path has a name. 

@dgearhart, is it possible to simplify or collapse these directions? 

Map:
![image](https://cloud.githubusercontent.com/assets/4380498/9284826/3d316fe6-4294-11e5-8ea9-7ca69ae43565.png)

JSON: 
valhalla.mapzen.com/route?json={"locations":[{"lat":34.417,"lon":-119.868},{"lat":34.417,"lon":-119.854}],"costing":"bicycle","costing_options":{"bicycle":{"bicycle_type":"Road","cycling_speed":17,"use_roads":0.1}}}&api_key=

Response:
{"trip":{"status":0,"status_message":"Found route between points","legs":[{"shape":"ywts`AxddscF?{L^wgDu@yC?cFGyWNik@GyBOgDGuEe@qG?sGMgDkAoHGsFO_J?}J?_I~DkKLeP{@wN{AsPqBiWm@qH?qQhHww@\\sFGeFOa\\gDcGe@gDdAsEnCgE?gCNgc@Fk`@O{A]iB}@{AkAyBO}@EyADmAFk@l@kBl@iB\\kA^yCd@wC?_^D{_@?{AyBcFcAkB?iCNiBd@{AxBuEFaR?sFD{UFyVFqHFqG?yBjA{AzAkA~CO`Hl@vHOjBzA","summary":{"length":1.405,"time":498},"maneuvers":[{"begin_shape_index":0,"length":0.276,"time":0,"type":1,"end_shape_index":3,"instruction":"Go east.","verbal_post_transition_instruction":"Continue for 300 meters.","verbal_pre_transition_instruction":"Go east."},{"begin_shape_index":3,"verbal_post_transition_instruction":"Continue for 50 meters.","time":18,"type":8,"end_shape_index":5,"instruction":"Continue.","length":0.047,"verbal_transition_alert_instruction":"Continue.","verbal_pre_transition_instruction":"Continue."},{"begin_shape_index":5,"verbal_post_transition_instruction":"Continue for 70 meters.","time":17,"type":8,"end_shape_index":7,"instruction":"Continue.","length":0.071,"verbal_transition_alert_instruction":"Continue.","verbal_pre_transition_instruction":"Continue."},{"begin_shape_index":7,"verbal_post_transition_instruction":"Continue for 20 meters.","time":5,"type":8,"end_shape_index":9,"instruction":"Continue.","length":0.018,"verbal_transition_alert_instruction":"Continue.","verbal_pre_transition_instruction":"Continue."},{"begin_shape_index":9,"verbal_post_transition_instruction":"Continue for 30 meters.","time":6,"type":8,"end_shape_index":11,"instruction":"Continue.","length":0.025,"verbal_transition_alert_instruction":"Continue.","verbal_pre_transition_instruction":"Continue."},{"begin_shape_index":11,"verbal_post_transition_instruction":"Continue for 70 meters.","time":22,"type":8,"end_shape_index":16,"instruction":"Continue.","length":0.067,"verbal_transition_alert_instruction":"Continue.","verbal_pre_transition_instruction":"Continue."},{"begin_shape_index":16,"verbal_post_transition_instruction":"Continue for 100 meters.","time":33,"type":9,"end_shape_index":21,"instruction":"Bear right.","length":0.111,"verbal_transition_alert_instruction":"Bear right.","verbal_pre_transition_instruction":"Bear right."},{"begin_shape_index":21,"verbal_post_transition_instruction":"Continue for 40 meters.","time":15,"type":8,"end_shape_index":22,"instruction":"Continue.","length":0.036,"verbal_transition_alert_instruction":"Continue.","verbal_pre_transition_instruction":"Continue."},{"begin_shape_index":22,"verbal_post_transition_instruction":"Continue for 10 meters.","time":4,"type":8,"end_shape_index":23,"instruction":"Continue.","length":0.014,"verbal_transition_alert_instruction":"Continue.","verbal_pre_transition_instruction":"Continue."},{"begin_shape_index":23,"verbal_post_transition_instruction":"Continue for 30 meters.","time":8,"type":9,"end_shape_index":24,"instruction":"Bear right.","length":0.027,"verbal_transition_alert_instruction":"Bear right.","verbal_pre_transition_instruction":"Bear right."},{"begin_shape_index":24,"verbal_post_transition_instruction":"Continue for 90 meters.","time":20,"type":9,"end_shape_index":25,"instruction":"Bear right.","length":0.085,"verbal_transition_alert_instruction":"Bear right.","verbal_pre_transition_instruction":"Bear right."},{"begin_shape_index":25,"verbal_post_transition_instruction":"Continue for 90 meters.","time":20,"type":8,"end_shape_index":30,"instruction":"Continue.","length":0.088,"verbal_transition_alert_instruction":"Continue.","verbal_pre_transition_instruction":"Continue."},{"begin_shape_index":30,"verbal_post_transition_instruction":"Continue for 30 meters.","time":14,"type":10,"end_shape_index":33,"instruction":"Turn right.","length":0.029,"verbal_transition_alert_instruction":"Turn right.","verbal_pre_transition_instruction":"Turn right."},{"begin_shape_index":33,"verbal_post_transition_instruction":"Continue for 50 meters.","time":18,"type":16,"end_shape_index":34,"instruction":"Bear left.","length":0.053,"verbal_transition_alert_instruction":"Bear left.","verbal_pre_transition_instruction":"Bear left."},{"begin_shape_index":34,"verbal_post_transition_instruction":"Continue for 50 meters.","time":18,"type":8,"end_shape_index":35,"instruction":"Continue.","length":0.049,"verbal_transition_alert_instruction":"Continue.","verbal_pre_transition_instruction":"Continue."},{"begin_shape_index":35,"verbal_post_transition_instruction":"Continue for 30 meters.","time":13,"type":16,"end_shape_index":41,"instruction":"Bear left.","length":0.029,"verbal_transition_alert_instruction":"Bear left.","verbal_pre_transition_instruction":"Bear left."},{"begin_shape_index":41,"verbal_post_transition_instruction":"Continue for 30 meters.","time":14,"type":9,"end_shape_index":47,"instruction":"Bear right.","length":0.028,"verbal_transition_alert_instruction":"Bear right.","verbal_pre_transition_instruction":"Bear right."},{"begin_shape_index":47,"verbal_post_transition_instruction":"Continue for 50 meters.","time":20,"type":16,"end_shape_index":49,"instruction":"Bear left.","length":0.053,"verbal_transition_alert_instruction":"Bear left.","verbal_pre_transition_instruction":"Bear left."},{"begin_shape_index":49,"verbal_post_transition_instruction":"Continue for 50 meters.","time":19,"type":8,"end_shape_index":50,"instruction":"Continue.","length":0.048,"verbal_transition_alert_instruction":"Continue.","verbal_pre_transition_instruction":"Continue."},{"begin_shape_index":50,"verbal_post_transition_instruction":"Continue for 30 meters.","time":13,"type":16,"end_shape_index":54,"instruction":"Bear left.","length":0.029,"verbal_transition_alert_instruction":"Bear left.","verbal_pre_transition_instruction":"Bear left."},{"begin_shape_index":54,"verbal_post_transition_instruction":"Continue for 50 meters.","time":18,"type":9,"end_shape_index":58,"instruction":"Bear right.","length":0.050,"verbal_transition_alert_instruction":"Bear right.","verbal_pre_transition_instruction":"Bear right."},{"begin_shape_index":58,"verbal_post_transition_instruction":"Continue for 80 meters.","time":24,"type":8,"end_shape_index":61,"instruction":"Continue.","length":0.080,"verbal_transition_alert_instruction":"Continue.","verbal_pre_transition_instruction":"Continue."},{"begin_shape_index":61,"verbal_post_transition_instruction":"Continue for 10 meters.","time":4,"type":8,"end_shape_index":62,"instruction":"Continue.","length":0.014,"verbal_transition_alert_instruction":"Continue.","verbal_pre_transition_instruction":"Continue."},{"begin_shape_index":62,"verbal_post_transition_instruction":"Continue for 20 meters.","time":11,"type":8,"end_shape_index":64,"instruction":"Continue.","length":0.018,"verbal_transition_alert_instruction":"Continue.","verbal_pre_transition_instruction":"Continue."},{"begin_shape_index":64,"time":4,"type":26,"end_shape_index":65,"instruction":"Enter the roundabout and take the 1st exit.","length":0.006,"verbal_transition_alert_instruction":"Enter roundabout.","verbal_pre_transition_instruction":"Enter the roundabout and take the 1st exit."},{"begin_shape_index":65,"length":0.006,"time":2,"type":27,"end_shape_index":66,"instruction":"Exit the roundabout.","verbal_post_transition_instruction":"Continue for less than 10 meters.","verbal_pre_transition_instruction":"Exit the roundabout."},{"begin_shape_index":66,"verbal_post_transition_instruction":"Continue for less than 10 meters.","time":5,"type":9,"end_shape_index":67,"instruction":"Bear right.","length":0.009,"verbal_transition_alert_instruction":"Bear right.","verbal_pre_transition_instruction":"Bear right."},{"begin_shape_index":67,"verbal_post_transition_instruction":"Continue for 40 meters.","time":75,"type":8,"end_shape_index":70,"instruction":"Continue.","length":0.039,"verbal_transition_alert_instruction":"Continue.","verbal_pre_transition_instruction":"Continue."},{"begin_shape_index":70,"time":0,"type":4,"end_shape_index":70,"instruction":"You have arrived at your destination.","length":0.000,"verbal_transition_alert_instruction":"You will arrive at your destination.","verbal_pre_transition_instruction":"You have arrived at your destination."}]}],"units":"kilometers","summary":{"length":1.405,"time":498},"locations":[{"lon":-119.867996,"lat":34.417000,"type":"break"},{"lon":-119.853996,"lat":34.417000,"type":"break"}]}}

**Comment by kevinkreiser** [comment]
thats an interesting case. maybe it should collapse if everything that intersects it IS named and the angles are all small then NOT calling out a manuever at each intersection does make sense. because youre staying on the only 'unnamed' thing there is so there isnt ambiguity (because the name doesnt change)

**Comment by dgearhart** [comment]
@rmglennon yes, it is possible to simplify these directions. Thanks for the test route - I added it to our bicycle routes test file. The directions have not been optimized for bicycle or pedestrian yet
