### ISSUE TITLE
Improve unnamed pedestrian and bicycle paths in narrative

### ISSUE THREAD

**Issue by dgearhart** [valhalla/odin#158]
For pedestrian travel mode on a footway - callout unnamed maneuvers as  a walkway, for example:
BEFORE
Turn right
AFTER
Turn right onto walkway

For bicycle travel mode on a cycleway - callout unnamed maneuvers as a cycleway, for example:
BEFORE
Turn right
AFTER
Turn right onto cycleway

**Comment by gknisely** [comment]
Maybe it should be cycle path.  Thoughts?

**Comment by dnesbitt61** [comment]
cycleway (?) - not sure I like the word path
