### ISSUE TITLE
Do not verbal alert for tiny interstitial streets

### ISSUE THREAD

**Issue by nvkelso** [valhalla/odin#176]
* **1.** From Mission gas station to SF State I get verbal alerted to turn right onto `Randall Street`, and then to continue for `40 meters` before turning left onto `San Jose Avenue`. I don't need to be told about the 40 meters part, the important thing is to make the immediate left onto `San Jose Ave`. By the time the 40 meters part is read out to me I'm missing my turn.

* http://valhalla.github.io/demos/routing/#loc=13,37.725108,-122.446489&locations=[{"lat":37.742128907718765,"lng":-122.42239236831664},{"lat":37.72431019335138,"lng":-122.4834394454956}]&costing="auto"

```
2: Turn right onto Randall Street.
VERBAL_ALERT: Turn right onto Randall Street.
VERBAL_PRE: Turn right onto Randall Street.
VERBAL_POST: Continue for 40 meters.
40 m
3: Turn left onto San Jose Avenue.
```
<img width="586" alt="screen shot 2016-01-14 at 08 16 56" src="https://cloud.githubusercontent.com/assets/853051/12329892/58512c64-ba97-11e5-9f6f-6e9c157c43ed.png">

* **2.** In the same route, the same thing happens in step 8 (see below) when I come off the highway `exit` ramp, onto the surface street (`San Jose Ave/CA 82` but that's not obvious or really relevant) for less than a city block and need to merge right immediately (that's key) for step 9 to turn right onto `Sagamore St`.

```
7: Take exit 50 on the right toward SR-82/Mission Street/Daly City/SR-1 North.
VERBAL_ALERT: Take exit 50 on the right.
VERBAL_PRE: Take exit 50 on the right toward State Route 82, Mission Street.
449 m
8: Continue on San Jose Avenue/CA 82.
VERBAL_ALERT: Continue on San Jose Avenue.
VERBAL_PRE: Continue on San Jose Avenue, California 82 for 40 meters.
44 m
9: Bear right onto Sagamore Street.
VERBAL_ALERT: Bear right onto Sagamore Street.
VERBAL_PRE: Bear right onto Sagamore Street.
VERBAL_POST: Continue for 600 meters.
622 
```

<img width="720" alt="screen shot 2016-01-14 at 08 23 26" src="https://cloud.githubusercontent.com/assets/853051/12330075/2db2ea14-ba98-11e5-92e9-999ac8a353d8.png">

* **3.** New route from Noe Valley to Cole Valley in SF. This one seems slightly different? If so, split out to new issue? Too many `Portola Drive` in quick sequence. 

* http://valhalla.github.io/demos/routing/#loc=16,37.755465,-122.439505&locations=[{"lat":37.743706929976675,"lng":-122.42670536041258},{"lat":37.76286109741452,"lng":-122.45223999023436}]&costing="auto"

```
5: Turn right onto Portola Drive.
VERBAL_ALERT: Turn right onto Portola Drive.
VERBAL_PRE: Turn right onto Portola Drive.
VERBAL_POST: Continue for 20 meters.
15 m
6: Bear left to stay on Portola Drive.
VERBAL_ALERT: Bear left to stay on Portola Drive.
VERBAL_PRE: Bear left to stay on Portola Drive.
VERBAL_POST: Continue for 90 meters.
93 m
7: Bear left to stay on Portola Drive.
VERBAL_ALERT: Bear left to stay on Portola Drive.
VERBAL_PRE: Bear left to stay on Portola Drive.
VERBAL_POST: Continue for 300 meters.
```

**Comment by dgearhart** [comment]
For the first issue above - we are expecting that the app would combine the two maneuver call-outs based on speed. Thus, it should say `Turn right onto Randall Street then Turn left onto San Jose Avenue.`

**Comment by nvkelso** [comment]
@ecgreb for comment.

**Comment by dgearhart** [comment]
For the second issue above - if possible, we might be able to suppress the continue maneuver. Similar to #157 
Otherwise, similar to issue one

**Comment by dgearhart** [comment]
split the third issue from above into #178 and #179

**Comment by dgearhart** [comment]
We will update the service: The service will still have two maneuvers but have a multi-cue VERBAL_PRE based on assumed time (i.e. travel mode and default speed).
Thus, the VERBAL_PRE for issue 1 maneuver 2 above would be: Turn right onto Randall Street then Turn left onto San Jose Avenue.
The app would still have to make a decision if the VERBAL_POST is needed based on current speed/location. 
How does this sound @ecgreb?

**Comment by nvkelso** [comment]
> Thus, the VERBAL_PRE for issue 1 maneuver 2 above would be: Turn right onto Randall Street then Turn left onto San Jose Avenue.

Nice!

**Comment by nvkelso** [comment]
I'm getting this a lot in SF during reroutes in Eraser Map in my drive & walk tests this weekend. Adding this note here because it seems to be a variation on this existing issue (beginning instead of intermediate steps).

I'm often presented with a "go 20 feet" or "go 200 feet", then turn onto the other street. But by the time voicebox tells me to "go X feet", I'm already at the turn but don't know to take the turn. 

For "new" routes that have initial segments less than 300 to 500 feet length, can we emphasize the immediate maneuver (left, right) instead in the verbal on continuing on the street for a few feet, then the maneuver? Is this a Valhalla task or an Eraser Map task?

Related, @ecgreb it would be "quicker" to have a rerouting "chime" sound effect and then give the instructions than to say the robot text of "rerouting..." before giving the new instructions? 

Examples:

Driving:
http://valhalla.github.io/demos/routing/#loc=15,37.716350,-122.488739&locations=[{"lat":37.71781802473407,"lng":-122.49992966651917},{"lat":37.74397841428505,"lng":-122.42666244506835}]&costing="auto"

Walking:
http://valhalla.github.io/demos/routing/#loc=17,37.760215,-122.419780&locations=[{"lat":37.758543783982816,"lng":-122.42069721221922},{"lat":37.769629187677,"lng":-122.42219924926756}]&costing="auto"

Walking 2:
http://valhalla.github.io/demos/routing/#loc=17,37.759494,-122.419501&locations=[{"lat":37.75678794789927,"lng":-122.41999447345734},{"lat":37.76966311138133,"lng":-122.42214560508727}]&costing="auto"

**Comment by dgearhart** [comment]
@nvkelso I believe this is releated to this Eraser Map isssue: mapzen/eraser-map#227
