### ISSUE TITLE
Do not say turn right if no intersection

### ISSUE THREAD

**Issue by nvkelso** [valhalla/odin#177]
From Noe Valley to Cole Valley, I'm told to turn right on `Clayton St`, but I'm already on Clayton St, and there's no other street to turn on. Seems weird to verbal alert for this.

* http://valhalla.github.io/demos/routing/#loc=16,37.758858,-122.446393&locations=[{"lat":37.743706929976675,"lng":-122.42670536041258},{"lat":37.76286109741452,"lng":-122.45223999023436}]&costing="auto"

```
10: Turn right to stay on Clayton Street.
VERBAL_ALERT: Turn right to stay on Clayton Street.
VERBAL_PRE: Turn right to stay on Clayton Street.
VERBAL_POST: Continue for 300 meters.
```

<img width="501" alt="screen shot 2016-01-14 at 08 30 37" src="https://cloud.githubusercontent.com/assets/853051/12330276/25bcb2da-ba99-11e5-8b18-7135df9880a2.png">

**Comment by dgearhart** [comment]
Both of these maneuvers are not corrrect The first should be a left and then second should be called out at the intersecting stairs. I might have another example like this 

`9: Continue on Clayton Street.
VERBAL_ALERT: Continue on Clayton Street.
VERBAL_PRE: Continue on Clayton Street for 300 meters.
10: Turn right to stay on Clayton Street.
VERBAL_ALERT: Turn right to stay on Clayton Street.
VERBAL_PRE: Turn right to stay on Clayton Street.
VERBAL_POST: Continue for 300 meters.`

**Comment by nvkelso** [comment]
Should that intersection be "valid" for car driving, though?

**Comment by dgearhart** [comment]
I missed a 'not' - i updated above. Maneuver 10 should be removed

**Comment by nvkelso** [comment]
Cool :)
