### ISSUE TITLE
Bike directions takes busy street instead of bike route

### ISSUE THREAD

**Issue by nvkelso** [valhalla/odin#180]
From my house to nearby bike store I was directed onto very busy Mission Street for a long block instead of the local signed bicycle route along Tiffany. It's shorter, and safer than taking Mission.

http://valhalla.github.io/demos/routing/#loc=15,37.749102,-122.417800&locations=[{"lat":37.74368996217435,"lng":-122.42670536041258},{"lat":37.756228107342615,"lng":-122.41855144500732}]&costing="auto"

<img width="262" alt="screen shot 2016-01-16 at 22 36 28" src="https://cloud.githubusercontent.com/assets/853051/12376329/4f1aa190-bca2-11e5-9b00-6942007de20c.png">

Tiffany street is correctly in a bicycle route relation, and the bike-only connection to Valencia St is correct: 

* https://www.openstreetmap.org/way/26378110
* https://www.openstreetmap.org/way/26378109

Interestingly, reversing the route correctly takes Tiffany!

http://valhalla.github.io/demos/routing/#loc=16,37.747864,-122.420193&locations=[{"lat":37.75610511150117,"lng":-122.42090106010436},{"lat":37.74367299436812,"lng":-122.42670536041258}]&costing="auto"

Even stranger, the recommended route is highly influenced by the intersection with Tiffany and 29th. Note how placing the start **east** of the intersection will take Tiffany, but **west** will skip the street.

It may be related to this "turn restriction"?

* https://www.openstreetmap.org/node/2399952061

But that doesn't appear like a normal turn restriction in iD [edit: I've gotten it to show up since], and it's not clear how to mark that a car-only turn restriction (to allow bicycle to turn left here).

_Note: The costing in the URL hash doesn't seem to update, but tapping the route mode options do update the map, and this was using the bicycle costing._

/cc @burritojustice

**Comment by nvkelso** [comment]
I'm suspicious of this turn restriction at all. I don't remember this being signed as such, and I don't see a sign in street view. 

But say it is valid for card, how do I mark it not valid for bicycles – and does Valhalla honor that?

**Comment by nvkelso** [comment]
Speculative data fix in: https://www.openstreetmap.org/changeset/36628413 to mark this turn restriction (if valid) as `access= motor_vehicle`.

**Comment by dgearhart** [comment]
hopefully turn restriction was the issue
path issues should be submitted under thor

**Comment by dnesbitt61** [comment]
Looks like Graphhopper does not honor turn restrictions at all for bicycles. While bicyclists often can and do turn anywhere they want I think the responsible thing to do is generally honor the rules of the road and if turns are not allowed by autos, then it is probably best not to allow them for bikes.

**Comment by dnesbitt61** [comment]
Seems to be fixed now.
