### ISSUE TITLE
Tests failed

### ISSUE THREAD

**Issue by ptpt** [valhalla/odin#321]
Noticed 3 tests failed in test-suite.log
```
TestBuildTurnInstructions_1_miles_cs_CZ  [FAIL: Incorrect maneuver verbal_post_transition_instruction - expected: Pokračujte 1,2 mil.  |  produced: Pokračujte 
1.2 mil.]
TestBuildTurnInstructions_1_miles_de_DE  [FAIL: Incorrect maneuver verbal_post_transition_instruction - expected: 1,2 Milen weiter.  |  produced: 1.2 Milen wei
ter.]
TestBuildTurnInstructions_1_miles_it_IT  [FAIL: Incorrect maneuver verbal_post_transition_instruction - expected: Continua per 1,2 miglia.  |  produced: Contin
ua per 1.2 miglia.]
```

Not sure if locale settings are related. Here is the output:
```
$ locale
LANG=
LANGUAGE=
LC_CTYPE="POSIX"
LC_NUMERIC="POSIX"
LC_TIME="POSIX"
LC_COLLATE="POSIX"
LC_MONETARY="POSIX"
LC_MESSAGES="POSIX"
LC_PAPER="POSIX"
LC_NAME="POSIX"
LC_ADDRESS="POSIX"
LC_TELEPHONE="POSIX"
LC_MEASUREMENT="POSIX"
LC_IDENTIFICATION="POSIX"
LC_ALL=
```
Doesn't work if I change `LANG`  to for example `en_US`.

**Comment by kevinkreiser** [comment]
Ah yes, we should add some instructions. Basically to make the tests pass you must install the locales that we are supporting. You can do so manually, or you can do this:

    scripts/install_locales.sh $(grep -F posix_locale locales/*.json | sed -e "s/.*locale[^a-z^A-Z]\+//g" -e "s/[^a-z^A-Z^0-9^.^_]\+//g")

The `dependencies.sh` script does it for you if you are installing odin via that.

**Comment by ptpt** [comment]
Tests passed! Thanks @kevinkreiser

**Comment by rossanag** [comment]
I did execute your script and my locale file was generated. The readme says I should do make check, but there's no a check file.
What am I missing? Thanks

**Comment by kevinkreiser** [comment]
maybe on your system it generates a `test` target in lieu of a `check` target. the two are synonymous though so you you should be good with `make test`

**Comment by dgearhart** [comment]
@rossanag could you submit a PR - maybe we could help with the tests?

**Comment by rossanag** [comment]
Oh I missed this message, I submit a PR
