### ISSUE TITLE
Alert instructions for roundabouts.

### ISSUE THREAD

**Issue by dnesbitt61** [valhalla/odin#351]
Support issue from quilkin:

a) If approaching a roundabout, the 'alert' instruction will be "enter the roundabout" and the 'pre' might be "enter the roundabout and take the third exit". But ideally we need to know which exit to take in the 'alert', in order to drive into the correct lane (many, if not most, roundabouts in Europe have a two-lane or three-lane entry). So I'm ignoring the 'alert' instructions and always using the 'pre', even when placed 50 metres before the turn.

**Comment by dgearhart** [comment]
@quilkin Could you provide an example for me to review?
Were you hoping that the alert would have the exit spoke number? And, the pre would have the exit spoke number and destination street name?

**Comment by quilkin** [comment]
@dgearhart Pretty much any roundabout near me would be examples, e.g. one at 50.26351 ,-5.04625 (routing SE  from St Austell St to Malpas Road), and one at 50.26458, -5.09459 (routing west along Tresawls Rd). Yes, the alert should have the spoke number. The destination street name probably not so important in the pre (if it's in the exit instruction), street names are rarely easy to spot on roundabouts

**Comment by dgearhart** [comment]
Thanks @quilkin - I will take a look
