### ISSUE TITLE
Extra maneuver instructions for 'straight on'?

### ISSUE THREAD

**Issue by quilkin** [valhalla/odin#352]
Would it be possible to add a 'straight on' or 'continue' instruction at junctions where there is no turn to be made and there has not been a turn for some time? Particularly if using the bicycle option, it would be good to give the user some assurance that he is still on track if there are no turns to be made for several kilometres. I could calculate and add 'continue for 500 metres' instructions at suitable points in the polyline, but it would be better to have these occurring at or just before junctions. I note (by inspecting the points on a polyline) that an extra point is always added at a junction, but there seems no way to distinguish these from other points (i.e. where the road just bends slightly). 
Another important use for these would be in instances where it is not clear (from the base map) if a maneuver is required or not. This can occur for example when a minor road joins a slightly more major one at a bend in the major one; the base map will not necessarily 'know' the priority of the junction and may fail to give a maneuver when one is required. 
If such 'continue' instructions were present is could be up to the designer to decide how often to use them.

**Comment by dnesbitt61** [comment]
I'm a little unclear on the purpose of adding verbal instructions at intermediate points where no maneuver exists. I'm not sure what assurance this would provide. The navigation app should know when you are off-route and will give indications that you are no longer on the original route. We will give continue and straight-on guidance when road names change. If there is no change in road name it seems that it would be bothersome to give what may be meaningless guidance. Also, you should be able to see the route highlighted on the base map to remove doubt in many cases.

**Comment by quilkin** [comment]
I think the title of my post might be misleading, sorry. Judging from inspecting points in a polyline, the design of the line creation clearly adds points where a junction exists, so presumably there was some reason for this. Yet there is (AFAIK) no way for the programmer to separate such points from others. An example of the potential use of this can be found at 50.25845, -5.07706 where no instruction is provided when travelling southwest, because 'Penwethers Lane' appears to continue striaight on. But the road layout here was changed after Penwethers Lane was named, and priority is now into 'Trethowan Heights'. OSM shows a slight bend in the road layout to reflect this. If it were possible for an app to determine that a junction exists at this bend, it could try to intelligently add an extra instruction, and/or switch on the device screen to show the manoeuvre. (In this particular case, relying on an 'off route' warning based on, say, 50 metres, would result in riding down a steep hill into a dead-end! )

**Comment by dnesbitt61** [comment]
We have deliberately not sent back "per edge" information as this adds a large amount of data to the route response. We are working on a map-matching API which will allow queries with route shape or GPS traces with various returns of intersection and edge attribution. This would allow an application to make custom decisions at various intersections.

**Comment by dgearhart** [comment]
If I understand you correctly - when travelling southwest on Penwethers Lane at 50.25845, -5.07706 - there should be a "Turn left to stay on Penwethers Lane"
The shape of the OSM ways was not very good in that area - I updated the way shape to match the roads. Hopefully, that will solve the issue

**Comment by quilkin** [comment]
Duane - yes, a 'left turn' is required here. I have seen your edit on OSM, and that should help in this instance, but that was just one example - I think I have experienced similar ones but need to check again. I guess it's mainly an OSM accuracy issue, but the API that David mentions sounds good.

**Comment by dgearhart** [comment]
@quilkin please let me know if you find other instances - if the shape is good, we could update the code to reflect reality

**Comment by dgearhart** [comment]
@quilkin production has been updated
http://www.openstreetmap.org/directions?engine=mapzen_car&route=50.25915%2C-5.07619%3B50.25791%2C-5.07763#map=19/50.25852/-5.07689
